const yaml = require('js-yaml')
const axios = require('axios')
const fs = require('fs')

const colorsDefinitionUrl =
    'https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml'

axios.get(colorsDefinitionUrl).then((res) => {
    const data = yaml.load(res.data)

    const languagesArr = Object.keys(data).map((languageKey) => {
        return {
            color: data[languageKey].color,
            language: languageKey,
        }
    })

    fs.writeFile(
        './src/helpers/languageColors.ts',
        `// This file was autogenerated by script/getGitHubColors.js
    export const languageColors = 
    ${JSON.stringify(languagesArr)}
    `,
        function (err) {
            if (err) throw err
            console.log('File is created successfully.')
        },
    )
})
